version: "3.8"

services:
  diskompala:
    container_name: diskompala-bot
    build: .
    image: diskompala
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - diskompala

networks:
  diskompala:
